import { Geologica } from "@next/font/google";
import "../../styles/globals.css";
import PropTypes from "prop-types";

const geologica = Geologica({
  subsets: ["latin"],
  variable: "--font-geologica",
});

export const metadata = {
  title: "Orientalize Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={geologica.variable}>
      <body>{children}</body>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.node.isRequired,
};
